[CI] Secret for preprod-submit-test-wallet.skey #145

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -53,16 +53,27 @@ jobs:
       uses: pre-commit/action@v3.0.0
       with:
         extra_args: --verbose --all-files
-    - name: Prepare Maestro config file
+    - name: Prepare config files
       env:
         MAESTRO_CONFIG: ${{secrets.MAESTRO_CONFIG}}
+        ATLAS_PREPROD_SKEY: ${{secrets.ATLAS_PREPROD_SKEY}}
       run: |
-          echo "Creating maestro-config.json..."
+          # MAESTRO_CONFIG ----------------------------------
+          echo "Creating maestro-config.json from MAESTRO_CONFIG env var..."
           echo "$MAESTRO_CONFIG" >> maestro-config.json
           if [[ -f maestro-config.json ]] ; then
             echo "[OK] maestro-config.json has been created."
           else
             echo "[ERROR] maestro-config.json is missing."
+            exit 1
+          fi
+          # PREPROD_SUBMIT_TEST_WALLET_SKEY ----------------------------------
+          echo "Creating preprod-submit-test-wallet.skey from PREPROD_SUBMIT_TEST_WALLET_SKEY env var..."
+          echo "$PREPROD_SUBMIT_TEST_WALLET_SKEY" >> preprod-submit-test-wallet.skey
+          if [[ -f preprod-submit-test-wallet.skey ]] ; then
+            echo "[OK] preprod-submit-test-wallet.skey has been created."
+          else
+            echo "[ERROR] preprod-submit-test-wallet.skey is missing."
             exit 1
           fi
     - name: Setup haskell tooling
